config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'

  get 'accounts/login' => 'accounts#login'
  get 'accounts/create'  => 'accounts#create'

  resources :events, only: [:index, :new, :create]
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  # title
  # description
  # date
  # location
  # street
  # city
  # state
  # postal_code
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/account_controller.rb
class AccountController < ApplicationController 
  def login
    render :login
  end
  
  def create
    render :create
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController 
  def login
    render :login
  end
  
  def create
    render :create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # Base Application controller
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order(date: :asc).page params[:page]

    render :index
  end

  def new
    render :new
  end

  def create
    redirect_to action: :index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/accounts/create.html.erb
<form>
  <div class="form-group">
    <label for="input-first-name">First name</label>
    <input type="text" class="form-control" id="input-first-name" placeholder="First name">
  </div>
  <div class="form-group">
    <label for="input-email">Last name</label>
    <input type="text" class="form-control" id="input-last-name" placeholder="Last name">
  </div>
  <div class="form-group">
    <label for="input-email">Email address</label>
    <input type="email" class="form-control" id="input-email" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="input-password">Password</label>
    <input type="password" class="form-control" id="input-password" placeholder="Password">
  </div>
	<div class="form-group">
    <label for="input-password-verify">Verify Password</label>
    <input type="password" class="form-control" id="input-password-verify" placeholder="Password">
  </div>
  
  <%= link_to "Cancel", {controller: :home, action: :index}, class: "btn btn-default pull-left" %>
  <%= link_to "Submit", {controller: :home, action: :index}, class: "btn btn-primary pull-right" %>
</form>

app/views/accounts/login.html.erb
<form>
  <div class="form-group">
    <label for="input-email">Email address</label>
    <input type="email" class="form-control" id="input-email" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="input-password">Password</label>
    <input type="password" class="form-control" id="input-password" placeholder="Password">
  </div>

  <%= link_to "Cancel", '/', class: "btn btn-default pull-left" %>
  <%= link_to "Submit", {controller: :home, action: :index}, class: "btn btn-primary pull-right" %>
</form>

app/views/events/index.html.erb
<h2>Events</h2>

<%= link_to new_event_path, class: 'btn btn-default ' do %>
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add event
<% end %>
<div id="event-list" class="list-group">
  <% @events.each do |event| %>
    <div class="list-group-item event">
      <div class="list-group-item-text event-date badge"><%= event.date.strftime(Rails.application.config.date_format) %></div>
      <h4 class="list-group-item-heading event-title"><%= event.title %></h4>
      <h5 class="list-group-item-heading event-description"><%= event.description %></h5>

      <div class="list-group-item-text event-location"><%= event.location %></div>
      <div class="list-group-item-text event-street"><%= event.street %></div>
      <div class="list-group-item-text event-region">
        <span class="event-city"><%= event.city %></span>
        <span class="event-state"><%= event.state %></span>
        <span class="event-postal-code"><%= event.postal_code %></span>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @events %>

app/views/events/new.html.erb
<h2>Create event</h2>

<%= form_for(:event) do |f| %>
  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, autofocus: true, placeholder: 'Title', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: 'Description', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.datetime_field :date, placeholder: 'Date', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, placeholder: 'Location description', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :street %>
    <%= f.text_field :street, placeholder: 'Street address', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, placeholder: 'City', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, placeholder: 'State', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code, placeholder: 'Postal code', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= link_to "Cancel", {controller: :home, action: :index}, class: "btn btn-default pull-left" %>
    <%= link_to "Create", {controller: :home, action: :index}, class: "btn btn-primary pull-right" %>
    <!--<%= f.submit "Create", class: "btn btn-primary pull-right" %>-->
  </div>
<% end %>

app/views/home/index.html.erb
<div id="map-canvas"></div>
<script type="text/javascript">
	main();
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Rurukish Est. 2015</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Rurukish', '/', class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Map<span class="sr-only">(current)</span></a></li>
        <li><a href="/events/">Events</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if @signed_in %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">DanceVenturer <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">My Events</a></li>
                <li><a href="#">Friends</a></li>
                <li><a href="#">Settings</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Sign out</a></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Sign in', accounts_login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rurukish</title>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9FT47ZdeSADxCb0_R3G6dz7pmXu7H0R8" type="text/javascript"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>